### ISSUE TITLE
Suggest Quotation Marks Conversion: From " " " to "「" and "」"

### ISSUE THREAD

**Issue by arthurartoria** [Hopkins1/TradSimpChinese#1]
Suggest Quotation Marks Conversion: From " " " to "「" and "」"

**Comment by Hopkins1** [comment]
Changing quotes or double quotes into Chinese quote marks is more complicated than it would seem at first.  I've seen the " symbol used in some Chinese texts that use traditional characters. It would also need to avoid changing any quoted text contained within HTML tags. It's doable, but it would take a fair amount of verification. I'll look into adding it as an option.

I see the title of this issue changed a couple of times. Just a reminder:

-After a conversion, the "File|Save" or "File|Save a copy" action needs to be completed in the editor tool before a epub file conversion is performed in the main Calibre window.

-Any changes occurring in "content.opf"  (such as the creator name or book title) are lost if the "File|Save" option is used on a file which was already added to Calibre. This is because Calibre keeps an internal database of all this data. The plugin leaves the database untouched. Consider doing "File|Save a copy" and adding that newly saved file to Calibre.

**Comment by Hopkins1** [comment]
Just added release 2.1.0 that will add the option to update quotation marks. Simplified to traditional conversions will work fairly well if curved "smart" quotes are used in the original text. All well-constructed simplified texts should use smart quotes.

**Comment by arthurartoria** [comment]
Thanks. This update is great. :D
