### ISSUE TITLE
metadata translate from simp to trad

### ISSUE THREAD

**Issue by ayeteng** [Hopkins1/TradSimpChinese#7]
Hi all,

Just find the metadata of the book will be re-written in Calibre when save the modified book. Therefore, all the translate from simp to trad will be lost. Is there any way to avoid such happen? Or need to submit a bug in Calibre there?

**Comment by Hopkins1** [comment]
As I understand it, when a book is added to the main Calibre program, the OPF file is read and the metadata is store in a separate database.

When the Calibre Editor is started via the main Calibre program, any changes made to the metadata in the Calibre Editor do not update the metadata in the Calibre database. The Editor does not have acess to the database.

But, there are 2 things that can be done to minimize the problem:

1.
In the Editor, **un-check** the "Update metadata embedded in the book when opening". The path is Help | Preferences | | Integrate with calibre
幫助(H) | 偏好設定(P) | Integration with calibre 
Now when the book is Editor is started via the main Calibre program, the database will not overwrite the metadata. 

2. Consider doing a "save a copy" to save the EPUB with the changed metadata. Use this copy for reading on your other devices.

Unfortunately, the database is not changed. I may need to rewrite the plugin so that it works directly in the main Calibre program. Then I think I could modify the database.

**Comment by ayeteng** [comment]
'Save a copy' probable the best choose that the moment. It's too heavy to rewrite the plugin cause it already very stable to me to convert between simp to trad.

Thanks for your reply.

**Comment by ayeteng** [comment]
"When the Calibre Editor is started via the main Calibre program, any changes made to the metadata in the Calibre Editor do not update the metadata in the Calibre database. The Editor does not have acess to the database."

Do you think if it's required to report it to Calibre? Or ask them to have a setting to allow editor in sync with the Calibre metadata database? if it's required, I would be glad to submit it.

**Comment by Hopkins1** [comment]
I've done some thinking about this. I'm not sure it would be a good idea to allow the editor to change the database metadata.
A particular book in the main GUI browser may have several different formats associated with the same metadata (i.e. EPUB, AZW3, MOBI, PDF, etc). The plugin only changes the text and metadata in one of these files. The other files are unchanged and would now have incorrect metadata. Now they would be out of sync.
